# .github/workflows/ansible-lint.yml
name: ansible-lint

on:
#  workflow_dispatch:
  push:

jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@main
      - name: first lint
        uses: ansible/ansible-lint-action@main
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main
